services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: phase-2-jenkins-pipeline-lab
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    restart: unless-stopped

volumes:
  jenkins_home: